name: test
run-name: ${{ github.actor }} - test
on: workflow_dispatch
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "log success message"
      - run: |
          echo "success" 
