name: hello-world
run-name: ${{ github.actor }} - print Hello World !
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
      - name: "[node]: execute automation [NAME]"
        run: |
          node src/tasks/helloworld/entry.ts
